version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: build image
          command: |
            # docker build includes tests
            docker build .
