version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: build image
          command: |
            # docker build includes tests
            docker build .
